import { Landmark, Cog, Headset, Users, Building2, Wrench, ShieldCheck, Megaphone } from "lucide-react";
import type {
  SummaryCardData,
  UnitData,
  TrendPoint,
  TopTeam,
  ActionTask,
  CategoryMeta,
  CategoryKey,
  Team,
  ExecutiveTeamSummary,
  TeamDrilldownStats,
} from "./types";
import {
  toTask,
  toLedgerTask,
  toMyPlanTask,
  toStandardTask,
  toDrillDownInitiative,
} from "./types";

// ---------------------------------------------------------------------------
// Dashboard: summary cards
// ---------------------------------------------------------------------------

export const SUMMARY_CARDS: SummaryCardData[] = [
  {
    id: "finance",
    label: "Finance",
    icon: Landmark,
    percent: 82,
  },
  {
    id: "process-tech",
    label: "Process / Tech",
    icon: Cog,
    percent: 64,
  },
  {
    id: "customer",
    label: "Customer",
    icon: Headset,
    percent: 91,
  },
  {
    id: "people",
    label: "People",
    icon: Users,
    percent: 77,
  },
];

// ---------------------------------------------------------------------------
// Dashboard: team performance units
// ---------------------------------------------------------------------------

export const UNITS: UnitData[] = [
  {
    id: "bu01",
    code: "BU01",
    overall: 88,
    metrics: [
      { label: "FIN", percent: 94 },
      { label: "TECH", percent: 82 },
      { label: "CUST", percent: 90 },
      { label: "PEOP", percent: 85 },
    ],
  },
  {
    id: "bu02",
    code: "BU02",
    overall: 52,
    metrics: [
      { label: "FIN", percent: 48, severity: "low" },
      { label: "TECH", percent: 31, severity: "critical" },
      { label: "CUST", percent: 65 },
      { label: "PEOP", percent: 64 },
    ],
  },
  {
    id: "bu03",
    code: "BU03",
    overall: 74,
    metrics: [
      { label: "FIN", percent: 70 },
      { label: "TECH", percent: 92 },
      { label: "CUST", percent: 80 },
      { label: "PEOP", percent: 55 },
    ],
  },
  {
    id: "bu04",
    code: "BU04",
    overall: 96,
    metrics: [
      { label: "FIN", percent: 98 },
      { label: "TECH", percent: 96 },
      { label: "CUST", percent: 84 },
      { label: "PEOP", percent: 96 },
    ],
  },
  {
    id: "engineering",
    name: "Engineering",
    overall: 81,
    metrics: [
      { label: "FIN", percent: 75 },
      { label: "TECH", percent: 84 },
      { label: "CUST", percent: 93 },
      { label: "PEOP", percent: 70 },
    ],
  },
  {
    id: "hr-admin",
    name: "HR & Administration",
    overall: 76,
    metrics: [
      { label: "FIN", percent: 62 },
      { label: "TECH", percent: 55 },
      { label: "CUST", percent: 74 },
      { label: "PEOP", percent: 59 },
    ],
  },
  {
    id: "finance-team",
    name: "Finance",
    overall: 61,
    metrics: [
      { label: "FIN", percent: 58 },
      { label: "TECH", percent: 44, severity: "low" },
      { label: "CUST", percent: 65 },
      { label: "PEOP", percent: 75 },
    ],
  },
  {
    id: "sales-marketing",
    name: "Sales & Marketing",
    overall: 85,
    metrics: [
      { label: "FIN", percent: 80 },
      { label: "TECH", percent: 70 },
      { label: "CUST", percent: 92 },
      { label: "PEOP", percent: 74 },
    ],
  },
];

// ---------------------------------------------------------------------------
// Dashboard: completion trend & top teams
// ---------------------------------------------------------------------------

export const TREND_DATA: TrendPoint[] = [
  { label: "W01", percent: 68 },
  { label: "W02", percent: 74 },
  { label: "W03", percent: 79 },
  { label: "W04", percent: 86 },
  { label: "W05 (Current)", percent: 91 },
];

export const TOP_TEAMS: TopTeam[] = [
  { id: "legal-risk", initials: "LR", name: "Legal/Risk", percent: 96 },
  { id: "global-sales", initials: "GS", name: "Global Sales", percent: 88 },
  { id: "sales-marketing", initials: "SM", name: "Sales & Marketing", percent: 85 },
];

// ---------------------------------------------------------------------------
// Tasks — single canonical catalog (derive all view-specific exports below)
// ---------------------------------------------------------------------------

export const CATEGORIES: CategoryMeta[] = [
  { key: "Finance", icon: Landmark, percent: 70 },
  { key: "Customer", icon: Headset, percent: 50 },
  { key: "Process/Tech", icon: Cog, percent: 85 },
  { key: "People", icon: Users, percent: 40 },
];

export const CATEGORY_SECTION_TITLES: Record<CategoryKey, string> = {
  Finance: "Finance & Allocation",
  Customer: "Customer & Market",
  "Process/Tech": "Process & Tech",
  People: "People & Talent",
};

export const TEAMS: Team[] = [
  { id: "bu01", label: "BU01 · North America Retail", icon: Building2 },
  { id: "bu02", label: "BU02 · EMEA Wholesale", icon: Building2 },
  { id: "engineering", label: "Engineering", icon: Wrench },
  { id: "hr-admin", label: "HR & Admin", icon: ShieldCheck },
  { id: "sales-marketing", label: "Sales & Marketing", icon: Megaphone },
];

export const TASKS: ActionTask[] = [
  // Action plan (org-wide)
  {
    id: "t1",
    description: "Reduce operational overhead in regional branches",
    kpi: ">95% Completion",
    frequency: "Monthly",
    category: "Finance",
    active: true,
    completed: false,
    scope: ["plan"],
  },
  {
    id: "t2",
    description: "Quarterly audit of procurement expenditures",
    kpi: "Zero Discrepancies",
    frequency: "Quarterly",
    category: "Finance",
    active: false,
    completed: true,
    scope: ["plan"],
  },
  {
    id: "t3",
    description: "Weekly response time monitoring for Tier 1 tickets",
    kpi: "<2hr Response",
    frequency: "Weekly",
    category: "Customer",
    active: true,
    completed: false,
    scope: ["plan"],
  },
  {
    id: "t4",
    description: "Migrate legacy reporting to real-time dashboards",
    kpi: "100% Real-time",
    frequency: "Monthly",
    category: "Process/Tech",
    active: true,
    completed: false,
    scope: ["plan"],
  },
  {
    id: "t5",
    description: "Monthly leadership coaching for BU01 team leads",
    kpi: "100% On-time",
    frequency: "Monthly",
    category: "People",
    active: true,
    completed: true,
    scope: ["plan"],
  },

  // Task ledger
  {
    id: "l1",
    description: "Finalize Q3 Budget Allocation",
    category: "Finance",
    statusNote: "Starts Oct 10",
    kpi: "OPEX Target",
    frequency: "Weekly",
    active: true,
    completed: false,
    owner: { initials: "SM", team: "Finance Core", color: "#3B82F6" },
    scope: ["ledger"],
  },
  {
    id: "l2",
    description: "Audit Supply Chain Invoices",
    category: "Finance",
    statusNote: "Completed Oct 02",
    kpi: "Cost Reduction",
    frequency: "Monthly",
    active: false,
    completed: true,
    owner: { initials: "AL", team: "Operations", color: "#6B7280" },
    scope: ["ledger"],
  },
  {
    id: "l3",
    description: "Vendor Contract Renewal Review",
    category: "Finance",
    statusNote: "Starts Oct 20",
    kpi: "Contract Compliance",
    frequency: "Quarterly",
    active: true,
    completed: false,
    owner: { initials: "FC", team: "Finance Core", color: "#3B82F6" },
    scope: ["ledger"],
  },
  {
    id: "l4",
    description: "Review CSAT Survey Feedback Q3",
    category: "Customer",
    statusNote: "Starts Oct 10",
    kpi: "NPS Score",
    frequency: "Quarterly",
    active: true,
    completed: false,
    priority: "High",
    owner: { initials: "JR", team: "Client Success", color: "#16233F" },
    scope: ["ledger"],
  },
  {
    id: "l5",
    description: "Cloud Migration Phase 2",
    category: "Process/Tech",
    statusNote: "Starts Oct 15",
    kpi: "System Uptime",
    frequency: "Monthly",
    active: true,
    completed: false,
    owner: { initials: "IT", team: "Technology", color: "#38BDF8" },
    scope: ["ledger"],
  },
  {
    id: "l6",
    description: "Q4 Performance Reviews",
    category: "People",
    statusNote: "Starts Nov 01",
    kpi: "Review Completion",
    frequency: "Quarterly",
    active: true,
    completed: false,
    owner: { initials: "HR", team: "People Ops", color: "#A855F7" },
    scope: ["ledger"],
  },
  {
    id: "l7",
    description: "Leadership Training Program",
    category: "People",
    statusNote: "Starts Oct 20",
    kpi: "Certification Rate",
    frequency: "Monthly",
    active: true,
    completed: false,
    owner: { initials: "LD", team: "Learning & Development", color: "#F97316" },
    scope: ["ledger"],
  },

  // My action plan — BU01
  {
    id: "m1",
    description: "Reconcile weekly cash position",
    category: "Finance",
    kpi: "Ledger Accuracy %",
    frequency: "Weekly",
    teamId: "bu01",
    source: "standard",
    active: true,
    completed: true,
    completedAt: "Mon 09:14",
    scope: ["my-plan"],
  },
  {
    id: "m2",
    description: "Submit variance commentary",
    category: "Finance",
    kpi: "Variance Reporting",
    frequency: "Weekly",
    teamId: "bu01",
    source: "standard",
    active: false,
    completed: false,
    scope: ["my-plan"],
  },
  {
    id: "m3",
    description: "Review top-10 customer health scores",
    category: "Customer",
    kpi: "NPS",
    frequency: "Weekly",
    teamId: "bu01",
    source: "standard",
    active: true,
    completed: true,
    completedAt: "Tue 11:02",
    scope: ["my-plan"],
  },
  {
    id: "m4",
    description: "Follow up on escalated tickets",
    category: "Customer",
    kpi: "Ticket Aging",
    frequency: "Weekly",
    teamId: "bu01",
    source: "standard",
    active: true,
    completed: false,
    scope: ["my-plan"],
  },
  {
    id: "m5",
    description: "Sprint retro action items closed",
    category: "Process/Tech",
    kpi: "Retro Closure",
    frequency: "Weekly",
    teamId: "bu01",
    source: "standard",
    active: true,
    completed: false,
    scope: ["my-plan"],
  },
  {
    id: "m6",
    description: "Deploy monthly patch bundle",
    category: "Process/Tech",
    kpi: "Patch SLA",
    frequency: "Monthly",
    teamId: "bu01",
    source: "standard",
    active: true,
    completed: false,
    scope: ["my-plan"],
  },
  {
    id: "m7",
    description: "Complete 1:1 with each direct report",
    category: "People",
    kpi: "1:1 Completion",
    frequency: "Weekly",
    teamId: "bu01",
    source: "standard",
    active: true,
    completed: true,
    completedAt: "Wed 15:20",
    scope: ["my-plan"],
  },
  {
    id: "m8",
    description: "Log recognition for peer contributions",
    category: "People",
    kpi: "Recognition Count",
    frequency: "Weekly",
    teamId: "bu01",
    source: "standard",
    active: true,
    completed: false,
    scope: ["my-plan"],
  },

  // My action plan — BU02
  {
    id: "m9",
    description: "Negotiate wholesale distributor terms",
    category: "Finance",
    kpi: "Margin Target",
    frequency: "Quarterly",
    teamId: "bu02",
    source: "standard",
    active: false,
    completed: false,
    owner: { initials: "DK", name: "David K.", team: "Finance / Planning" },
    scope: ["my-plan", "initiative"],
  },
  {
    id: "m10",
    description: "Localize product catalog for EU launch",
    category: "Process/Tech",
    kpi: "Localization Coverage",
    frequency: "Monthly",
    teamId: "bu02",
    source: "standard",
    active: true,
    completed: false,
    owner: { initials: "EH", name: "Elena H.", team: "Tech / Process" },
    scope: ["my-plan", "initiative"],
  },
  {
    id: "m11",
    description: "Onboard new EMEA support reps",
    category: "People",
    kpi: "Onboarding Completion",
    frequency: "Monthly",
    teamId: "bu02",
    source: "standard",
    active: true,
    completed: true,
    completedAt: "Thu 13:40",
    scope: ["my-plan"],
  },

  // My action plan — Engineering
  {
    id: "m12",
    description: "Fix critical auth bug in staging",
    category: "Process/Tech",
    kpi: "Bug Resolution SLA",
    frequency: "Weekly",
    teamId: "engineering",
    source: "standard",
    active: true,
    completed: true,
    completedAt: "Mon 10:02",
    owner: { initials: "TL", name: "Tom L.", team: "Process / Tech" },
    scope: ["my-plan", "initiative"],
  },
  {
    id: "m13",
    description: "Clear code review backlog",
    category: "Process/Tech",
    kpi: "Review Turnaround",
    frequency: "Weekly",
    teamId: "engineering",
    source: "standard",
    active: true,
    completed: false,
    owner: { initials: "PR", name: "Priya R.", team: "Process / Tech" },
    scope: ["my-plan", "initiative"],
  },
  {
    id: "m14",
    description: "Update on-call rotation doc",
    category: "People",
    kpi: "Doc Freshness",
    frequency: "Monthly",
    teamId: "engineering",
    source: "standard",
    active: true,
    completed: false,
    scope: ["my-plan"],
  },

  // My action plan — HR & Admin
  {
    id: "m15",
    description: "Process Q4 payroll adjustments",
    category: "Finance",
    kpi: "Payroll Accuracy",
    frequency: "Monthly",
    teamId: "hr-admin",
    source: "standard",
    active: false,
    completed: false,
    owner: { initials: "KW", name: "Kim W.", team: "Finance / Planning" },
    scope: ["my-plan", "initiative"],
  },
  {
    id: "m16",
    description: "Run quarterly engagement survey",
    category: "People",
    kpi: "Survey Response Rate",
    frequency: "Quarterly",
    teamId: "hr-admin",
    source: "standard",
    active: true,
    completed: false,
    owner: { initials: "RB", name: "Ravi B.", team: "People / Compliance" },
    scope: ["my-plan", "initiative"],
  },

  // My action plan — Sales & Marketing
  {
    id: "m17",
    description: "Finalize Q4 campaign budget",
    category: "Finance",
    kpi: "Budget Variance",
    frequency: "Quarterly",
    teamId: "sales-marketing",
    source: "standard",
    active: true,
    completed: false,
    owner: { initials: "CG", name: "Chloe G.", team: "Finance / Planning" },
    scope: ["my-plan", "initiative"],
  },
  {
    id: "m18",
    description: "Review lead conversion funnel",
    category: "Customer",
    kpi: "Conversion Rate",
    frequency: "Weekly",
    teamId: "sales-marketing",
    source: "standard",
    active: true,
    completed: true,
    completedAt: "Tue 14:00",
    owner: { initials: "OM", name: "Omar M.", team: "Customer / Growth" },
    scope: ["my-plan", "initiative"],
  },
  {
    id: "m19",
    description: "Refresh brand messaging deck",
    category: "Process/Tech",
    kpi: "Deck Completion",
    frequency: "Monthly",
    teamId: "sales-marketing",
    source: "standard",
    active: true,
    completed: false,
    owner: { initials: "LS", name: "Lena S.", team: "Process / Tech" },
    scope: ["my-plan", "initiative"],
  },

  // Executive drill-down only (BU01)
  {
    id: "d1",
    description: "Implement Automated Reporting",
    category: "Process/Tech",
    kpi: "Report Cycle Time",
    frequency: "Monthly",
    teamId: "bu01",
    active: true,
    completed: true,
    owner: { initials: "SJ", name: "Sarah J.", team: "Tech / Process" },
    scope: ["initiative"],
  },
  {
    id: "d2",
    description: "Q4 Resource Allocation Review",
    category: "Finance",
    kpi: "Budget Variance",
    frequency: "Quarterly",
    teamId: "bu01",
    active: false,
    completed: false,
    owner: { initials: "MT", name: "Michael T.", team: "Finance / Planning" },
    scope: ["initiative"],
  },
  {
    id: "d3",
    description: "Customer Escalation Response Time",
    category: "Customer",
    kpi: "Response SLA",
    frequency: "Weekly",
    teamId: "bu01",
    active: true,
    completed: false,
    owner: { initials: "JR", name: "Jamie R.", team: "Customer / Support" },
    scope: ["initiative"],
  },
  {
    id: "d4",
    description: "Warehouse Safety Audit",
    category: "People",
    kpi: "Audit Pass Rate",
    frequency: "Quarterly",
    teamId: "bu01",
    active: true,
    completed: true,
    owner: { initials: "AL", name: "Alex L.", team: "People / Compliance" },
    scope: ["initiative"],
  },

  // Executive drill-down only (BU02)
  {
    id: "d7",
    description: "Freight Delay Escalation Process",
    category: "Process/Tech",
    kpi: "On-Time Delivery",
    frequency: "Weekly",
    teamId: "bu02",
    active: false,
    completed: false,
    owner: { initials: "NP", name: "Nadia P.", team: "Process / Tech" },
    scope: ["initiative"],
  },

  // Standard task manage-tasks templates
  {
    id: "st1",
    description: "Monthly Financial Reconciliation",
    details: "Ensure all BU ledgers match corporate master.",
    category: "Finance",
    kpi: "Ledger Accuracy %",
    frequency: "Monthly",
    teamId: "bu01",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
  {
    id: "st2",
    description: "Quarterly Performance Reviews",
    details: "Conduct and log 1:1 reviews for all direct reports.",
    category: "People",
    kpi: "Completion Rate",
    frequency: "Quarterly",
    teamId: "hr-admin",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
  {
    id: "st3",
    description: "Weekly Customer NPS Survey",
    details: "Send NPS pulse to top 50 accounts.",
    category: "Customer",
    kpi: "NPS Score",
    frequency: "Weekly",
    teamId: "sales-marketing",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
  {
    id: "st4",
    description: "Sprint Retrospective",
    details: "Facilitate retro and log improvement items.",
    category: "Process/Tech",
    kpi: "Action Items Closed",
    frequency: "Bi-weekly",
    teamId: "engineering",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
  {
    id: "st5",
    description: "Vendor Compliance Audit",
    details: "Verify vendor contracts and SLAs.",
    category: "Process/Tech",
    kpi: "Audit Pass Rate",
    frequency: "Monthly",
    teamId: "bu02",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
  {
    id: "st6",
    description: "Payroll Accuracy Check",
    details: "Cross-check payroll runs against HRIS records.",
    category: "Finance",
    kpi: "Payroll Accuracy %",
    frequency: "Monthly",
    teamId: "hr-admin",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
  {
    id: "st7",
    description: "Customer Escalation Review",
    details: "Review all Tier 1 escalations from the past week.",
    category: "Customer",
    kpi: "Escalation Resolution Time",
    frequency: "Weekly",
    teamId: "bu01",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
  {
    id: "st8",
    description: "Security Patch Rollout",
    details: "Apply and verify latest security patches.",
    category: "Process/Tech",
    kpi: "Patch Compliance %",
    frequency: "Monthly",
    teamId: "engineering",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
  {
    id: "st9",
    description: "New Hire Onboarding Checklist",
    details: "Complete onboarding steps for new starters.",
    category: "People",
    kpi: "Onboarding Completion",
    frequency: "Weekly",
    teamId: "hr-admin",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
  {
    id: "st10",
    description: "Budget Variance Report",
    details: "Prepare variance commentary for leadership review.",
    category: "Finance",
    kpi: "Variance Accuracy",
    frequency: "Monthly",
    teamId: "bu02",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
  {
    id: "st11",
    description: "Customer Health Score Review",
    details: "Review health scores for top accounts at risk.",
    category: "Customer",
    kpi: "At-Risk Accounts Resolved",
    frequency: "Bi-weekly",
    teamId: "sales-marketing",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
  {
    id: "st12",
    description: "Employee Engagement Pulse",
    details: "Distribute and analyze short engagement survey.",
    category: "People",
    kpi: "Response Rate",
    frequency: "Quarterly",
    teamId: "hr-admin",
    source: "standard",
    active: true,
    completed: false,
    scope: ["standard"],
  },
];

export const INITIAL_TASKS = TASKS.filter((t) => t.scope.includes("plan")).map(toTask);
export const LEDGER_TASKS = TASKS.filter((t) => t.scope.includes("ledger")).map(toLedgerTask);
export const MY_PLAN_TASKS = TASKS.filter((t) => t.scope.includes("my-plan")).map(toMyPlanTask);
export const STANDARD_TASKS = TASKS.filter((t) => t.scope.includes("standard")).map(toStandardTask);

function initiativesForTeam(teamId: string) {
  return TASKS.filter((t) => t.teamId === teamId && t.scope.includes("initiative")).map(
    toDrillDownInitiative
  );
}

// ---------------------------------------------------------------------------
// Executive Summary: aggregate KPI cards
// ---------------------------------------------------------------------------

export const EXEC_SUMMARY_CARDS: SummaryCardData[] = [
  {
    id: "finance",
    label: "Finance",
    icon: Landmark,
    percent: 87,
  },
  {
    id: "customer",
    label: "Customer",
    icon: Headset,
    percent: 92,
  },
  {
    id: "process-tech",
    label: "Process/Tech",
    icon: Cog,
    percent: 76,
  },
  {
    id: "people",
    label: "People",
    icon: Users,
    percent: 89,
  },
];

// ---------------------------------------------------------------------------
// Executive Summary: per-team rollup (feeds the team cards list)
// ---------------------------------------------------------------------------

export const TEAM_SUMMARIES: ExecutiveTeamSummary[] = [
  {
    teamId: "bu01",
    overall: 88,
    status: "On Track",
    metrics: [
      { category: "Finance", percent: 90 },
      { category: "Customer", percent: 95 },
      { category: "Process/Tech", percent: 75, severity: "low" },
      { category: "People", percent: 92 },
    ],
  },
  {
    teamId: "bu02",
    overall: 74,
    status: "Needs Attention",
    metrics: [
      { category: "Finance", percent: 72, severity: "low" },
      { category: "Customer", percent: 88 },
      { category: "Process/Tech", percent: 60, severity: "critical" },
      { category: "People", percent: 76, severity: "low" },
    ],
  },
  {
    teamId: "engineering",
    overall: 81,
    status: "On Track",
    metrics: [
      { category: "Finance", percent: 70 },
      { category: "Customer", percent: 66 },
      { category: "Process/Tech", percent: 94 },
      { category: "People", percent: 94 },
    ],
  },
  {
    teamId: "hr-admin",
    overall: 79,
    status: "On Track",
    metrics: [
      { category: "Finance", percent: 81 },
      { category: "Customer", percent: 70 },
      { category: "Process/Tech", percent: 68, severity: "low" },
      { category: "People", percent: 96 },
    ],
  },
  {
    teamId: "sales-marketing",
    overall: 68,
    status: "Pending",
    metrics: [
      { category: "Finance", percent: 58, severity: "critical" },
      { category: "Customer", percent: 84 },
      { category: "Process/Tech", percent: 62, severity: "low" },
      { category: "People", percent: 68, severity: "low" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Executive Summary: read-only team drill-downs
// ---------------------------------------------------------------------------

export const TEAM_DRILLDOWNS: Record<string, TeamDrilldownStats> = {
  bu01: {
    teamId: "bu01",
    totalTasks: 186,
    completed: 142,
    completedTrendLabel: "+12% vs last month",
    currentlyActive: 31,
    incomplete: 13,
    performanceIndex: 78,
    initiatives: initiativesForTeam("bu01"),
  },
  bu02: {
    teamId: "bu02",
    totalTasks: 142,
    completed: 88,
    completedTrendLabel: "-4% vs last month",
    currentlyActive: 34,
    incomplete: 20,
    performanceIndex: 64,
    initiatives: initiativesForTeam("bu02"),
  },
  engineering: {
    teamId: "engineering",
    totalTasks: 97,
    completed: 71,
    completedTrendLabel: "+6% vs last month",
    currentlyActive: 18,
    incomplete: 8,
    performanceIndex: 81,
    initiatives: initiativesForTeam("engineering"),
  },
  "hr-admin": {
    teamId: "hr-admin",
    totalTasks: 64,
    completed: 49,
    completedTrendLabel: "+3% vs last month",
    currentlyActive: 11,
    incomplete: 4,
    performanceIndex: 79,
    initiatives: initiativesForTeam("hr-admin"),
  },
  "sales-marketing": {
    teamId: "sales-marketing",
    totalTasks: 118,
    completed: 61,
    completedTrendLabel: "-9% vs last month",
    currentlyActive: 28,
    incomplete: 29,
    performanceIndex: 68,
    initiatives: initiativesForTeam("sales-marketing"),
  },
};
